[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "flatten"
version = "1.0.0"
authors = [
  { name="Sean Quinlan", email="squinlan@astranis.com" },
]
description = "(Un)flatten telemetry packets."
requires-python = ">=3.8"